# Generated by Django 6.0.4 on 2026-04-17 17:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandaloneRace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('race_type', models.CharField(choices=[('training', 'Treino'), ('standalone', 'Avulsa')], default='standalone', max_length=15)),
                ('track_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField()),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('kart_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_laps', models.PositiveIntegerField(blank=True, null=True)),
                ('best_lap_time', models.CharField(blank=True, max_length=20, null=True)),
                ('total_time', models.CharField(blank=True, max_length=20, null=True)),
                ('average_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('gap_to_leader', models.CharField(blank=True, max_length=20, null=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='standalone_races', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'standalone_races',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StandaloneRaceTelemetry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lap_number', models.PositiveIntegerField()),
                ('lap_time', models.CharField(max_length=20)),
                ('kart_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gap_to_best', models.CharField(blank=True, max_length=20, null=True)),
                ('gap_to_leader', models.CharField(blank=True, max_length=20, null=True)),
                ('total_time', models.CharField(blank=True, max_length=20, null=True)),
                ('average_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sector1', models.CharField(blank=True, max_length=20, null=True)),
                ('sector2', models.CharField(blank=True, max_length=20, null=True)),
                ('sector3', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('standalone_race', models.ForeignKey(db_column='standalone_race_id', on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='races.standalonerace')),
            ],
            options={
                'db_table': 'standalone_race_telemetry',
                'ordering': ['lap_number'],
            },
        ),
    ]
