# Generated by Django 6.0.4 on 2026-04-17 17:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('championships', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_name', models.CharField(default='Award', max_length=100)),
                ('color', models.CharField(default='#FFD700', max_length=50)),
                ('is_automatic', models.BooleanField(default=False, null=True)),
                ('auto_condition', models.CharField(blank=True, max_length=500, null=True)),
                ('show_preview', models.BooleanField(default=True)),
                ('custom_image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('championship', models.ForeignKey(blank=True, db_column='championship_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge_definitions', to='championships.championship')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='profiles.profile')),
            ],
            options={
                'db_table': 'badge_definitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DriverBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('badge_type', models.CharField(max_length=100)),
                ('badge_name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(blank=True, db_column='awarded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='profiles.profile')),
                ('badge_definition', models.ForeignKey(blank=True, db_column='badge_definition_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_badges', to='badges.badgedefinition')),
                ('championship', models.ForeignKey(blank=True, db_column='championship_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='championships.championship')),
                ('profile', models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='profiles.profile')),
            ],
            options={
                'db_table': 'driver_badges',
                'ordering': ['-earned_at'],
            },
        ),
    ]
