# Generated by Django 6.0.4 on 2026-04-17 17:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('championships', '0001_initial'),
        ('profiles', '0001_initial'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('in_progress', 'Em Andamento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('championship', models.ForeignKey(db_column='championship_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='championships.championship')),
                ('track', models.ForeignKey(blank=True, db_column='track_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tracks.track')),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Heat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('weather_condition', models.CharField(blank=True, choices=[('dry', 'Seco'), ('wet', 'Molhado'), ('mixed', 'Misto')], default='dry', max_length=10, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='heats', to='events.event')),
            ],
            options={
                'db_table': 'heats',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='HeatResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driver_name_text', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('kart_number', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ('best_lap_time', models.CharField(blank=True, max_length=20, null=True)),
                ('total_time', models.CharField(blank=True, max_length=20, null=True)),
                ('gap_to_leader', models.CharField(blank=True, max_length=20, null=True)),
                ('gap_to_previous', models.CharField(blank=True, max_length=20, null=True)),
                ('average_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_laps', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_status', models.BooleanField(default=False, null=True)),
                ('points', models.PositiveIntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, db_column='driver_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heat_results', to='profiles.profile')),
                ('heat', models.ForeignKey(db_column='heat_id', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='events.heat')),
            ],
            options={
                'db_table': 'heat_results',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='LapTelemetry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lap_number', models.PositiveIntegerField()),
                ('lap_time', models.CharField(max_length=20)),
                ('sector1', models.CharField(blank=True, max_length=20, null=True)),
                ('sector2', models.CharField(blank=True, max_length=20, null=True)),
                ('sector3', models.CharField(blank=True, max_length=20, null=True)),
                ('kart_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gap_to_best', models.CharField(blank=True, max_length=20, null=True)),
                ('gap_to_leader', models.CharField(blank=True, max_length=20, null=True)),
                ('total_time', models.CharField(blank=True, max_length=20, null=True)),
                ('average_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('heat_result', models.ForeignKey(db_column='heat_result_id', on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='events.heatresult')),
            ],
            options={
                'db_table': 'lap_telemetry',
                'ordering': ['lap_number'],
            },
        ),
    ]
