# Generated by Django 6.0.4 on 2026-04-17 17:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('rules_summary', models.CharField(blank=True, max_length=10000, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(blank=True, db_column='organizer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_championships', to='profiles.profile')),
            ],
            options={
                'db_table': 'championships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChampionshipMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('pending', 'Pendente'), ('banned', 'Banido')], default='pending', max_length=10)),
                ('role', models.CharField(choices=[('driver', 'Piloto'), ('admin', 'Admin'), ('organizer', 'Organizador')], default='driver', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('championship', models.ForeignKey(db_column='championship_id', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='championships.championship')),
                ('profile', models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='championship_memberships', to='profiles.profile')),
            ],
            options={
                'db_table': 'championship_members',
                'unique_together': {('championship', 'profile')},
            },
        ),
    ]
