# Generated by Django 6.0.4 on 2026-04-17 17:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureVisibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_key', models.CharField(max_length=100, unique=True)),
                ('min_tier', models.CharField(choices=[('free', 'Free'), ('user', 'User'), ('plus', 'Plus'), ('moderator', 'Moderador'), ('admin', 'Admin')], default='free', max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feature_visibility',
                'ordering': ['label'],
            },
        ),
    ]
