# Generated by Django 6.0.4 on 2026-04-19 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PilotProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('modality', models.CharField(choices=[('rental', 'Rental'), ('profissional', 'Profissional'), ('endurance', 'Endurance')], max_length=20)),
                ('position_finished', models.IntegerField()),
                ('total_competitors', models.IntegerField()),
                ('best_lap_time', models.IntegerField(help_text='Em milissegundos')),
                ('total_time', models.IntegerField(help_text='Em milissegundos')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_public', models.BooleanField(default=True)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='pilots.pilotprofile')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='pilots.track')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to='pilots.pilotprofile')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_set', to='pilots.pilotprofile')),
            ],
            options={
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
